// ═══════════════════════════════════════════════════
// All portfolio data — skills, projects, toolkit, trainer info
// ═══════════════════════════════════════════════════

export const skills = [
  {
    id: '001', name: 'JAVASCRIPT', type: 'ELECTRIC', type2: 'FRONTEND',
    sprite: '⚡', flavor: 'The backbone of everything I build. Fast, versatile, and always evolving.',
    height: '5 yrs', weight: '30+ projects',
    stats: { hp: 95, atk: 90, def: 85, spAtk: 88, spDef: 82, speed: 90 },
    evolution: ['ES5', 'ES6+', 'TypeScript'],
    shiny: true,
  },
  {
    id: '002', name: 'REACT', type: 'FIRE', type2: 'FRONTEND',
    sprite: '🔥', flavor: 'My go-to weapon for building dynamic interfaces. Component-driven perfection.',
    height: '4 yrs', weight: '25+ projects',
    stats: { hp: 92, atk: 88, def: 80, spAtk: 92, spDef: 85, speed: 88 },
    evolution: ['Class Components', 'Hooks', 'Server Components'],
    shiny: true,
  },
  {
    id: '003', name: 'NEXT.JS', type: 'DRAGON', type2: 'FULLSTACK',
    sprite: '🐉', flavor: 'The evolution of React. Server-side rendering and beyond.',
    height: '3 yrs', weight: '15+ projects',
    stats: { hp: 88, atk: 85, def: 82, spAtk: 90, spDef: 80, speed: 85 },
    evolution: ['Pages Router', 'App Router', 'Server Actions'],
  },
  {
    id: '004', name: 'NODE.JS', type: 'WATER', type2: 'BACKEND',
    sprite: '💧', flavor: 'The bridge between frontend thinking and backend power.',
    height: '4 yrs', weight: '20+ projects',
    stats: { hp: 85, atk: 82, def: 78, spAtk: 85, spDef: 80, speed: 88 },
    evolution: ['Express', 'Fastify', 'NestJS'],
  },
  {
    id: '005', name: 'PYTHON', type: 'GRASS', type2: 'BACKEND',
    sprite: '🌿', flavor: 'Clean, readable, and devastatingly effective for data & automation.',
    height: '3 yrs', weight: '15+ projects',
    stats: { hp: 80, atk: 75, def: 72, spAtk: 88, spDef: 78, speed: 70 },
    evolution: ['Scripts', 'Django', 'FastAPI'],
  },
  {
    id: '006', name: 'CSS', type: 'PSYCHIC', type2: 'FRONTEND',
    sprite: '🧠', flavor: 'Not just styling—architecture. Grid, Flexbox, animations, the whole arsenal.',
    height: '5 yrs', weight: '30+ projects',
    stats: { hp: 90, atk: 85, def: 88, spAtk: 92, spDef: 85, speed: 82 },
    evolution: ['Float Layouts', 'Flexbox', 'Grid + Custom Props'],
    shiny: true,
  },
  {
    id: '007', name: 'TYPESCRIPT', type: 'ROCK', type2: 'FULLSTACK',
    sprite: '🪨', flavor: 'Type safety that catches bugs before they hatch. Essential for scale.',
    height: '2 yrs', weight: '12+ projects',
    stats: { hp: 78, atk: 80, def: 90, spAtk: 82, spDef: 88, speed: 72 },
    evolution: ['Basic Types', 'Generics', 'Type Gymnastics'],
  },
  {
    id: '008', name: 'GIT', type: 'DARK', type2: 'DEVOPS',
    sprite: '⚫', flavor: 'Version control mastery. Branching, rebasing, and conflict resolution.',
    height: '5 yrs', weight: '40+ projects',
    stats: { hp: 85, atk: 78, def: 92, spAtk: 70, spDef: 90, speed: 80 },
    evolution: ['Commit', 'Branch', 'Rebase + CI/CD'],
  },
  {
    id: '009', name: 'MONGODB', type: 'WATER', type2: 'BACKEND',
    sprite: '💧', flavor: 'Document-based storage that adapts to any shape of data.',
    height: '3 yrs', weight: '10+ projects',
    stats: { hp: 82, atk: 75, def: 80, spAtk: 78, spDef: 82, speed: 85 },
    evolution: ['CRUD', 'Aggregation', 'Atlas + Indexing'],
  },
  {
    id: '010', name: 'FIGMA', type: 'NORMAL', type2: 'DESIGN',
    sprite: '✨', flavor: 'Where ideas take visual form before a single line of code is written.',
    height: '3 yrs', weight: '20+ projects',
    stats: { hp: 75, atk: 80, def: 70, spAtk: 90, spDef: 72, speed: 88 },
    evolution: ['Wireframes', 'Components', 'Design Systems'],
  },
];

export const projects = [
  {
    name: 'PORTFOLIO V2',
    species: 'FULL-STACK APP',
    level: 45,
    hp: { current: 142, max: 142 },
    type: 'FIRE',
    type2: 'DRAGON',
    status: 'OK',
    held: 'NEXT.JS + VERCEL',
    ot: 'ATHAR',
    idNo: '2025',
    moves: [
      { name: 'PIXEL RENDER', type: 'FIRE', pp: '60fps', power: 95 },
      { name: 'RESPONSIVE', type: 'WATER', pp: '100% coverage', power: 90 },
      { name: 'SOUND ENGINE', type: 'ELECTRIC', pp: '6 effects', power: 85 },
      { name: 'KEYBOARD NAV', type: 'PSYCHIC', pp: 'Full a11y', power: 88 },
    ],
  },
  {
    name: 'AUCTION SYS',
    species: 'WEB APPLICATION',
    level: 38,
    hp: { current: 118, max: 118 },
    type: 'WATER',
    type2: 'ROCK',
    status: 'OK',
    held: 'NEXT.JS + MONGODB',
    ot: 'ATHAR',
    idNo: '2024',
    moves: [
      { name: 'REAL-TIME BID', type: 'ELECTRIC', pp: '<50ms', power: 92 },
      { name: 'AUTH SYSTEM', type: 'DARK', pp: 'JWT + RBAC', power: 88 },
      { name: 'PUZZLE ENGINE', type: 'PSYCHIC', pp: '50+ puzzles', power: 85 },
      { name: 'TEAM MANAGE', type: 'NORMAL', pp: '20 teams', power: 80 },
    ],
  },
  {
    name: 'CHAT REALM',
    species: 'REALTIME APP',
    level: 32,
    hp: { current: 98, max: 105 },
    type: 'ELECTRIC',
    status: 'SLP',
    held: 'SOCKET.IO + NODE',
    ot: 'ATHAR',
    idNo: '2023',
    moves: [
      { name: 'WEBSOCKET', type: 'ELECTRIC', pp: '<10ms', power: 95 },
      { name: 'CHANNELS', type: 'WATER', pp: '∞ rooms', power: 82 },
      { name: 'ENCRYPT MSG', type: 'DARK', pp: 'E2E', power: 90 },
      { name: 'FILE SHARE', type: 'NORMAL', pp: '10MB max', power: 75 },
    ],
  },
  {
    name: 'TASK FORGE',
    species: 'PRODUCTIVITY APP',
    level: 28,
    hp: { current: 88, max: 88 },
    type: 'GRASS',
    status: 'OK',
    held: 'REACT + FIREBASE',
    ot: 'ATHAR',
    idNo: '2023',
    moves: [
      { name: 'DRAG & DROP', type: 'PSYCHIC', pp: 'Smooth 60fps', power: 85 },
      { name: 'COLLAB EDIT', type: 'FIRE', pp: '5 users', power: 80 },
      { name: 'NOTIF SYSTEM', type: 'ELECTRIC', pp: 'Push + Email', power: 78 },
      { name: 'DARK MODE', type: 'DARK', pp: 'Auto detect', power: 72 },
    ],
  },
  {
    name: 'API GATEWAY',
    species: 'MICROSERVICE',
    level: 35,
    hp: { current: 110, max: 110 },
    type: 'ROCK',
    type2: 'WATER',
    status: 'FRZ',
    held: 'EXPRESS + REDIS',
    ot: 'ATHAR',
    idNo: '2024',
    moves: [
      { name: 'RATE LIMIT', type: 'ROCK', pp: '1K req/s', power: 88 },
      { name: 'CACHE LAYER', type: 'WATER', pp: '95% hit', power: 92 },
      { name: 'LOAD BALANCE', type: 'NORMAL', pp: '3 nodes', power: 85 },
      { name: 'HEALTH CHECK', type: 'GRASS', pp: '99.9% up', power: 80 },
    ],
  },
  {
    name: 'ML PREDICT',
    species: 'DATA PIPELINE',
    level: 25,
    hp: { current: 72, max: 80 },
    type: 'PSYCHIC',
    status: 'BRN',
    held: 'PYTHON + SKLEARN',
    ot: 'ATHAR',
    idNo: '2022',
    moves: [
      { name: 'DATA CLEAN', type: 'WATER', pp: '10K rows', power: 80 },
      { name: 'MODEL TRAIN', type: 'PSYCHIC', pp: '94% acc', power: 90 },
      { name: 'VISUALIZE', type: 'FIRE', pp: '12 charts', power: 78 },
      { name: 'DEPLOY API', type: 'ROCK', pp: 'Flask REST', power: 75 },
    ],
  },
];

export const toolkit = {
  items: [
    { name: 'VS CODE', desc: 'Primary code editor. Extensions for every language.', qty: '∞' },
    { name: 'TERMINAL', desc: 'Bash + Zsh. Where the real work happens.', qty: '∞' },
    { name: 'FIGMA', desc: 'UI/UX design and prototyping tool.', qty: '∞' },
    { name: 'POSTMAN', desc: 'API testing and documentation platform.', qty: '∞' },
    { name: 'CHROME DEVTOOLS', desc: 'Debugging, profiling, network analysis.', qty: '∞' },
  ],
  keyItems: [
    { name: 'REACT', desc: 'Core UI library. Component-driven architecture.', qty: '★' },
    { name: 'NEXT.JS', desc: 'Full-stack React framework. SSR + SSG.', qty: '★' },
    { name: 'NODE.JS', desc: 'Server-side JavaScript runtime.', qty: '★' },
    { name: 'JAVASCRIPT', desc: 'The language that powers everything.', qty: '★' },
    { name: 'MONGODB', desc: 'NoSQL database for flexible data.', qty: '★' },
  ],
  pokeBalls: [
    { name: 'RUST', desc: 'Systems programming. Currently learning.', qty: '~' },
    { name: 'GO', desc: 'Concurrent backend services. In progress.', qty: '~' },
    { name: 'THREE.JS', desc: '3D rendering for the web. Experimenting.', qty: '~' },
  ],
  tms: [
    { name: 'TM01 — DOCKER', desc: 'Containerization for consistent environments.', qty: '×5' },
    { name: 'TM02 — AWS', desc: 'Cloud infrastructure and deployment.', qty: '×3' },
    { name: 'TM03 — CI/CD', desc: 'GitHub Actions, automated pipelines.', qty: '×8' },
    { name: 'TM04 — REST API', desc: 'API design principles and patterns.', qty: '×20' },
    { name: 'TM05 — GRAPHQL', desc: 'Query language for flexible data fetching.', qty: '×4' },
  ],
  berries: [
    { name: 'COMMUNICATION', desc: 'Clear technical writing and team collaboration.', qty: '★' },
    { name: 'PROBLEM SOLVING', desc: 'Breaking complex problems into manageable pieces.', qty: '★' },
    { name: 'FAST LEARNER', desc: 'Pick up new frameworks and concepts quickly.', qty: '★' },
    { name: 'TEAM PLAYER', desc: 'Collaborative, supportive, and adaptable.', qty: '★' },
  ],
};

export const trainerInfo = {
  name: 'ATHAR',
  idNo: '2020',
  money: '@ DEVELOPER',
  pokedex: skills.length,
  time: '4:32',
  badges: [
    { name: 'Boulder Badge', desc: 'First project shipped', earned: true },
    { name: 'Cascade Badge', desc: 'First freelance work', earned: true },
    { name: 'Thunder Badge', desc: 'First dev position', earned: true },
    { name: 'Rainbow Badge', desc: 'Reached 1000+ users', earned: true },
    { name: 'Soul Badge', desc: 'Open source contributor', earned: true },
    { name: 'Marsh Badge', desc: 'Led a team project', earned: true },
    { name: 'Volcano Badge', desc: 'Project featured online', earned: true },
    { name: 'Earth Badge', desc: 'Building something big...', earned: false },
  ],
  bio: 'A passionate developer who loves crafting pixel-perfect interfaces and robust backends. Obsessed with clean code and creative UX. Always leveling up.',
  links: {
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    email: 'hello@example.com',
  },
};
