// ═══════════════════════════════════════════════════
// All portfolio data — skills, projects, toolkit, trainer info
// ═══════════════════════════════════════════════════

export const skills = [
  { id: '001', name: 'MONGODB', type: 'PSYCHIC', sprite: '🍃', flavor: 'NoSQL database for flexible, schema-less data storage.', stats: { hp: 75, atk: 60, def: 65, spAtk: 90, spDef: 70, speed: 80 } },
  { id: '002', name: 'EXPRESS.JS', type: 'NORMAL', sprite: '🚂', flavor: 'Fast, unopinionated web framework that forms the backend routing backbone.', stats: { hp: 70, atk: 65, def: 60, spAtk: 80, spDef: 65, speed: 90 } },
  { id: '003', name: 'REACT.JS', type: 'FIRE', sprite: '⚛️', flavor: 'Component-driven frontend library for building highly dynamic user interfaces.', stats: { hp: 80, atk: 70, def: 65, spAtk: 95, spDef: 75, speed: 88 } },
  { id: '004', name: 'NODE.JS', type: 'WATER', sprite: '🟩', flavor: 'Server-side JavaScript runtime powering scalable and fast backend services.', stats: { hp: 85, atk: 75, def: 70, spAtk: 85, spDef: 70, speed: 92 } },
  { id: '005', name: 'C', type: 'STEEL', sprite: '⚙️', flavor: 'The grandfather of modern languages. Offers raw memory control and extreme efficiency.', stats: { hp: 60, atk: 95, def: 90, spAtk: 70, spDef: 80, speed: 95 } },
  { id: '006', name: 'C++', type: 'STEEL', type2: 'FIGHTING', sprite: '🗡️', flavor: 'Object-oriented power designed for performance-critical logic.', stats: { hp: 65, atk: 100, def: 85, spAtk: 80, spDef: 75, speed: 90 } },
  { id: '007', name: 'C#', type: 'STEEL', type2: 'PSYCHIC', sprite: '🔷', flavor: 'Versatile and strongly typed, perfect for enterprise solutions and game development.', stats: { hp: 75, atk: 85, def: 80, spAtk: 88, spDef: 85, speed: 78 } },
  { id: '008', name: 'JAVA', type: 'GROUND', sprite: '☕', flavor: 'Write once, run anywhere. The heavyweight champion of robust architecture.', stats: { hp: 90, atk: 80, def: 85, spAtk: 82, spDef: 88, speed: 65 } },
  { id: '009', name: 'JAVASCRIPT', type: 'ELECTRIC', sprite: '⚡', flavor: 'The spark that powers the interactive web. Fast, chaotic, and essential.', stats: { hp: 78, atk: 85, def: 60, spAtk: 92, spDef: 65, speed: 98 } },
  { id: '010', name: 'PYTHON', type: 'GRASS', type2: 'POISON', sprite: '🐍', flavor: 'Clean syntax for rapid scripting, automation, and backend logic.', stats: { hp: 82, atk: 70, def: 65, spAtk: 95, spDef: 75, speed: 72 } },
  { id: '011', name: 'TYPESCRIPT', type: 'ROCK', sprite: '🪨', flavor: 'Catches bugs before they hatch with strict, reliable type safety.', stats: { hp: 80, atk: 78, def: 90, spAtk: 88, spDef: 92, speed: 70 } },
  { id: '012', name: 'POSTGRESQL', type: 'GROUND', type2: 'WATER', sprite: '🐘', flavor: 'The steadfast titan of relational databases. Handles complex joins effortlessly.', stats: { hp: 95, atk: 70, def: 90, spAtk: 85, spDef: 88, speed: 60 } },
  { id: '013', name: 'MYSQL', type: 'WATER', sprite: '🐬', flavor: 'Reliable and widely used open-source relational database management.', stats: { hp: 88, atk: 65, def: 85, spAtk: 80, spDef: 82, speed: 68 } },
  { id: '014', name: 'NEXT.JS', type: 'DRAGON', sprite: '🐉', flavor: 'The ultimate React framework for production-grade applications.', stats: { hp: 90, atk: 85, def: 80, spAtk: 98, spDef: 85, speed: 88 } },
  { id: '015', name: 'THREE.JS', type: 'PSYCHIC', type2: 'ICE', sprite: '🧊', flavor: 'Harnessing the power of WebGL to create immersive 3D experiences in the browser.', stats: { hp: 72, atk: 70, def: 65, spAtk: 100, spDef: 80, speed: 85 } },
  { id: '016', name: 'ASSEMBLY', type: 'STEEL', type2: 'GHOST', sprite: '📟', flavor: 'The soul of the machine. Speaking directly to the CPU with zero abstraction.', stats: { hp: 50, atk: 110, def: 80, spAtk: 50, spDef: 60, speed: 120 } },
  { id: '017', name: 'HTML5', type: 'NORMAL', sprite: '🧱', flavor: 'The structural skeleton and absolute foundation of the internet.', stats: { hp: 70, atk: 50, def: 75, spAtk: 60, spDef: 65, speed: 55 } },
  { id: '018', name: 'CSS3', type: 'FAIRY', sprite: '🎨', flavor: 'Bringing style, grid layouts, and smooth animations to the browser.', stats: { hp: 68, atk: 55, def: 70, spAtk: 88, spDef: 72, speed: 78 } },
  { id: '019', name: 'PHP', type: 'BUG', sprite: '🐘', flavor: 'Classic server-side scripting that continues to power a massive chunk of the web.', stats: { hp: 72, atk: 60, def: 65, spAtk: 75, spDef: 68, speed: 70 } },
  { id: '020', name: 'RUST', type: 'DRAGON', type2: 'STEEL', sprite: '🦀', flavor: 'Memory-safe systems programming that runs blazingly fast.', stats: { hp: 70, atk: 98, def: 95, spAtk: 85, spDef: 92, speed: 98 } },
];

export const projects = [
  {
    name: 'LEVELERS',
    species: 'COLLAB PLATFORM',
    level: 45,
    hp: { current: 142, max: 142 },
    type: 'ELECTRIC',
    type2: 'STEEL',
    status: 'OK',
    held: 'NEXT.JS + AZURE',
    ot: 'ATHARVA',
    idNo: '2028',
    moves: [
      { name: 'BRIDGE GAP', type: 'NORMAL', pp: 'Freelancers & SMEs', power: 90 },
      { name: 'AZURE DEPLOY', type: 'FLYING', pp: 'Cloud Host', power: 85 },
      { name: 'POSTGRES SYNC', type: 'GROUND', pp: 'Data Store', power: 88 },
    ],
    flavor: 'Developed a digital platform designed to bridge the gap between freelancers and Small & Medium Enterprises (SMEs). Enabled SMEs to boost their digital presence.',
    tech: ['Next.js', 'Postgres', 'Azure'],
    impact: 'Empowers SMEs to digitize workflows and find niche talent.'
  },
  {
    name: 'SEMANTIC STRUCTURE GENERATOR',
    species: 'GENERATIVE 3D ENV',
    level: 52,
    hp: { current: 168, max: 168 },
    type: 'DRAGON',
    type2: 'PSYCHIC',
    status: 'OK',
    held: 'REACT THREE FIBER + FLASK',
    ot: 'ATHARVA',
    idNo: '2027',
    moves: [
      { name: 'GEMINI ARCHITECT', type: 'PSYCHIC', pp: 'LLM Blueprint', power: 98 },
      { name: 'JSON SCHEMA', type: 'STEEL', pp: 'Structured Data', power: 92 },
      { name: 'REACT RENDER', type: 'ELECTRIC', pp: 'Real-time 3D', power: 95 },
    ],
    flavor: 'A generative 3D environment that transforms semantic text prompts into complex composite structures. Leverages Gemini 2.5 Flash to architect detailed blueprints.',
    tech: ['R3F', 'Gemini API', 'Flask'],
    impact: 'Automated 3D composition from plain English descriptors.'
  },
  {
    name: 'ECHO TERRAIN VISUALIZER',
    species: '3D AUDIO TERRAIN',
    level: 50,
    hp: { current: 160, max: 160 },
    type: 'PSYCHIC',
    type2: 'ICE',
    status: 'OK',
    held: 'THREE.JS + VITE',
    ot: 'ATHARVA',
    idNo: '2026',
    moves: [
      { name: 'FFT ANALYSIS', type: 'ELECTRIC', pp: 'Frequency Bands', power: 96 },
      { name: 'TERRAIN MESH', type: 'GROUND', pp: '14k+ Grid Points', power: 94 },
      { name: 'WATER SHADER', type: 'WATER', pp: 'Cinematic Bowl', power: 90 },
    ],
    flavor: 'A high-fidelity real-time 3D audio visualizer that transforms sound into a dynamic, shifting landscape. Maps frequency data to procedurally generated terrain.',
    tech: ['Three.js', 'Web Audio API', 'GLSL'],
    impact: 'Unique terrain landscapes generated per audio track.'
  }
];

export const toolkit = {
  items: [
    { name: 'VS CODE', desc: 'The command center. Heavy keybindings and essential extensions.', qty: '∞' },
    { name: 'NEOVIM', desc: 'For editing code blazingly fast without ever touching the mouse.', qty: '∞' },
    { name: 'LINUX', desc: 'The open-source kernel of freedom. Preferred environment for development.', qty: '∞' },
    { name: 'WINDOWS', desc: 'The versatile OS for gaming and specific enterprise software workflows.', qty: '∞' },
    { name: 'PYCHARM', desc: 'The professional IDE for Python development and data science.', qty: '∞' },
    { name: 'PHP STORM', desc: 'Deeply understands your code, provides best-in-class completion.', qty: '∞' },
    { name: 'GIT', desc: 'Time travel for code. Branching, rebasing, and merging workflows.', qty: '∞' },
    { name: 'DOCKER', desc: 'Shipping "it works on my machine" securely to production environments.', qty: '∞' },
    { name: 'POSTMAN', desc: 'Testing API endpoints relentlessly until they behave perfectly.', qty: '∞' },
    { name: 'MATLAB', desc: 'The language of technical computing and mathematical modeling.', qty: '∞' },
    { name: 'FIGMA', desc: 'Where the UI/UX magic happens before a single line of code is written.', qty: '∞' },
    { name: 'BLENDER', desc: 'Creating 3D models and assets for immersive Three.js scenes.', qty: '∞' },
    { name: 'GIMP', desc: 'The free and open-source image editor for asset manipulation.', qty: '∞' },
    { name: 'ECLIPSE', desc: 'The classic, heavy-duty IDE environment.', qty: '∞' },
    { name: 'GITHUB', desc: 'The multiplayer server for open-source and personal repositories.', qty: '∞' },
  ],
  keyItems: [
    { name: 'MECHANICAL KEYBOARD', desc: 'Loud clicks, high APM (Actions Per Minute). Essential for deep focus.', qty: '1' },
    { name: 'CAFFEINE ELIXIR', desc: 'Restores developer HP during late-night deployments. Flavored like a white energy drink.', qty: '99' },
    { name: 'SPOTIFY PREMIUM', desc: 'Blocks out distractions. The official soundtrack for entering the flow state.', qty: '1' },
    { name: 'RUBBER DUCK', desc: 'The ultimate debugging companion. Explaining code to it solves 90% of issues.', qty: '1' },
    { name: 'DEVTOOLS LENS', desc: 'Allows the user to see the hidden DOM structure and network requests of the web.', qty: '1' },
  ],
  berries: [
    { name: 'CONSTRUCTIVE CRITIQUE', desc: 'Instantly spots bugs or design flaws and suggests clean, actionable fixes.', qty: '★' },
    { name: 'ADAPTABILITY', desc: 'Allows the user to shape-shift and pick up entirely new tech stacks rapidly.', qty: '★' },
    { name: 'CREATIVE PROBLEM SOLVING', desc: 'Thinking outside the div when standard algorithms just won\'t cut it.', qty: '★' },
    { name: 'UNYIELDING POSITIVITY', desc: 'Prevents the "Burnout" status condition, keeping morale high across the team.', qty: '★' },
  ],
  pokeBalls: [
    { name: 'POKE BALL - HTML/CSS/JS', desc: 'Tier 1 foundation stack for standard web interfaces and interaction logic.', qty: '99' },
    { name: 'POKE BALL - REACT', desc: 'Tier 1 component architecture for scalable frontend development.', qty: '90' },
    { name: 'POKE BALL - VITE', desc: 'Tier 1 lightning-fast development server and build pipeline.', qty: '80' },
    { name: 'GREAT BALL - NEXT.JS', desc: 'Tier 2 full-stack React framework for SSR, routing, and production apps.', qty: '48' },
    { name: 'GREAT BALL - TAILWIND CSS', desc: 'Tier 2 utility-first styling system for rapid UI composition.', qty: '45' },
    { name: 'GREAT BALL - NES.CSS', desc: 'Tier 2 retro styling toolkit for pixel-perfect game-inspired UI.', qty: '30' },
    { name: 'GREAT BALL - LEAFLET', desc: 'Tier 2 mapping library for interactive geospatial web views.', qty: '24' },
    { name: 'ULTRA BALL - FRAMER MOTION', desc: 'Tier 3 animation framework for declarative UI motion and transitions.', qty: '32' },
    { name: 'ULTRA BALL - GSAP', desc: 'Tier 3 timeline-grade animation engine for cinematic interaction sequences.', qty: '28' },
    { name: 'ULTRA BALL - ANIME.JS', desc: 'Tier 3 lightweight animation library for micro-interactions and SVG motion.', qty: '26' },
    { name: 'ULTRA BALL - THREE.JS', desc: 'Tier 3 WebGL framework powering interactive 3D scenes and effects.', qty: '34' },
    { name: 'ULTRA BALL - REACT THREE FIBER', desc: 'Tier 3 React renderer that makes Three.js scenes component-driven.', qty: '22' },
    { name: 'ULTRA BALL - DREI', desc: 'Tier 3 helper toolkit for controls, loaders, and reusable 3D utilities.', qty: '18' },
    { name: 'TIMER BALL - NODE.JS', desc: 'Tier 3 JavaScript runtime for backend services and tooling.', qty: '40' },
    { name: 'TIMER BALL - EXPRESS.JS', desc: 'Tier 3 backend framework for REST APIs and middleware pipelines.', qty: '34' },
    { name: 'TIMER BALL - BUN', desc: 'Tier 3 high-performance JavaScript runtime and package manager.', qty: '20' },
    { name: 'TIMER BALL - FLASK', desc: 'Tier 3 lightweight Python web framework for APIs and prototyping.', qty: '25' },
    { name: 'TIMER BALL - FASTAPI', desc: 'Tier 3 modern Python API framework with strong typing and speed.', qty: '16' },
    { name: 'NET BALL - NUMPY', desc: 'Tier 2 numerical computing core for vectors, matrices, and data pipelines.', qty: '50' },
    { name: 'NET BALL - PANDAS', desc: 'Tier 2 dataframe toolkit for data wrangling and structured analysis.', qty: '42' },
    { name: 'NET BALL - MATPLOTLIB', desc: 'Tier 2 plotting suite for scientific charts and diagnostics.', qty: '36' },
    { name: 'NET BALL - VISPY', desc: 'Tier 2 high-performance interactive visualization leveraging GPU rendering.', qty: '14' },
    { name: 'NET BALL - MANIM', desc: 'Tier 2 mathematical animation engine for explanatory and technical visuals.', qty: '12' },
    { name: 'MASTER BALL - RUST', desc: 'Tier 4 systems language for memory-safe, high-performance modules.', qty: '6' },
    { name: 'MASTER BALL - C++', desc: 'Tier 4 performance-critical language for graphics-heavy and low-level code.', qty: '5' },
    { name: 'MASTER BALL - WEBASSEMBLY', desc: 'Tier 4 bridge for running near-native modules directly in the browser.', qty: '4' },
  ],
  tms: [
    { name: 'git commit -m', desc: 'Saves the current progress with a descriptive label.', qty: '∞' },
    { name: 'npm install', desc: 'Summons all required dependencies for the current project.', qty: '∞' },
    { name: 'gcc -o main', desc: 'Compiles raw C code into a powerful executable.', qty: '∞' },
    { name: 'sudo apt update', desc: 'Refreshes the local repository list on Linux systems.', qty: '∞' },
    { name: 'git push origin', desc: 'Sends local commits to the remote master server.', qty: '∞' },
    { name: 'npm run dev', desc: 'Ignites the local development server for instant feedback.', qty: '∞' },
    { name: 'cd ..', desc: 'Navigates one level up in the file system hierarchy.', qty: '∞' },
    { name: 'ls -la', desc: 'Reveals all hidden files and details in the current directory.', qty: '∞' },
    { name: 'git checkout -b', desc: 'Creates a parallel universe (branch) for new features.', qty: '∞' },
    { name: 'rm -rf node_modules', desc: 'The ultimate destruction move to clear corrupted dependencies.', qty: '∞' },
    { name: 'ssh user@host', desc: 'Remote teleports into a distant server environment.', qty: '∞' },
    { name: 'docker-compose up', desc: 'Orchestrates multiple containers to work in harmony.', qty: '∞' },
    { name: 'grep -r', desc: 'Searches through every file to find a specific string of text.', qty: '∞' },
    { name: 'man [command]', desc: 'Consults the ancient scrolls for manual instructions.', qty: '∞' },
    { name: 'curl -X GET', desc: 'Pokes an API endpoint to see what data it returns.', qty: '∞' },
    { name: 'ps aux | grep', desc: 'Identifies and tracks running background processes.', qty: '∞' },
    { name: 'chmod +x', desc: 'Grants the power of execution to a dormant script.', qty: '∞' },
    { name: 'git stash', desc: 'Temporarily hides current changes to clear the workspace.', qty: '∞' },
    { name: 'python3 -m venv', desc: 'Creates an isolated sanctuary for Python dependencies.', qty: '∞' },
    { name: 'cat /etc/os-release', desc: 'Identifies the soul and version of the Linux distro.', qty: '∞' },
    { name: 'history', desc: 'Looks back at every command ever cast in the current session.', qty: '∞' },
    { name: 'kill -9', desc: 'Forcefully terminates a stubborn or frozen process.', qty: '∞' },
    { name: 'npm audit fix', desc: 'Heals vulnerabilities within the project dependencies.', qty: '∞' },
  ],
};

export const trainerInfo = {
  name: 'ATHARVA SHERAMKAR',
  idNo: '05-11-06',
  money: '@ SDE INTERN',
  pokedex: skills.length,
  time: '99:99',
  badges: [
    { name: 'Startup Badge', desc: 'Fullstack SDE at Fundora', earned: true },
    { name: 'Visualizer Badge', desc: 'Mastered 3D Audio Visuals', earned: true },
    { name: 'Platform Badge', desc: 'Developed the Levelers platform', earned: true },
    { name: 'Vidyalankar Badge', desc: 'Batch of 2028 Computer Engineering', earned: false },
  ],
  bio: 'Ambitious Computer Engineering undergraduate (Batch of 2028) with a strong foundation in software development. Gamer, tech enthusiast, and full-stack developer passionate about building scalable digital solutions.',
  links: {
    github: 'https://github.com/UnstableBlob',
    linkedin: 'https://www.linkedin.com/in/atharva-sheramkar-93a930351',
    email: 'atharva20453@gmail.com',
  },
};